version: '3'

services:
  frontend_prod:
    build:
      context: .
      dockerfile: ./dockerfiles/production/Dockerfile
    container_name: opendata_frontend_prod
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=opendata.nonstopintegration.ml
      - LETSENCRYPT_HOST=opendata.nonstopintegration.ml
      - LETSENCRYPT_EMAIL=nonstopintegration@gmail.com

networks:
  default:
    external:
      name: webproxy
